# -*- coding: utf-8 -*-
"""Copy of video second.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SyXzY3pQ3I_T3oKJ3qzAj424bD_98r9m
"""

#Arithmatic operator
print(5+6)
print(5*6)
print(5/2)
print(5//2)#integer type division
print(5%2)
print(5**2)#yani five ki power two

"""#relational operator"""

#relational operator
print(2<5)
print(2>5)
print(2<=5)
print(5==6)
print(2>=5)
print(2==2)

"""#Logical operator

"""

#logical operator
print(2 and 0)
print(2 and 3)
print(5 or 10)
print(5 or 0)
print(0 or 5)
print(0 or 0 or 9)
print(2 and 6 and 5)
print(not  1 )
print(not 0)

"""#bitwise operator"""

#bitwise operator

#bitwisewise and
print(2 & 3)
#bitwisewise or
print(2 | 3)
#bitwise xor
print(2 ^ 3)# xor me same me zero aur diffent me 1
print(2 ^ 2)
#bitwise xnor
print(~3)
#bitwise left shift operator
print(2 >> 4)
print(4 >> 2)
#bitwise right shift operator
print(2 << 4)
print(4 << 3 )
#Assignment operator
a=2
# a=a+2
a+=2
print(a)
#second
a=2
#that means a=a%2
a%=2
print(a)# eska matlab a ka 2 ke sath modulas ho rha hai aur a me hi store ho ja rha  hai.

#membership
#in/not in
print('d' in 'delhi')#delhi me d hai ya nhi
print('d' not in 'delhi')
print(1 in [1,2,3,4,5,6,7])
print('D' in 'delhi')

#program
number=int(input("enter the 3 digit number= "))
#345%10 krne pr 5melega
a=number%10
number=number//10 #yaha 45 ka integer division krne pr 5 melega
#34%10 krne pr 4 melega
b=number%10
number=number//10# yaha 4 ka integer division krne pr 4 mel rha hai
#3%10 krne pr 3 melega
c=number%10
print(a+b+c)


#program for enter 6 digit number and add its bit
number=int(input('Enter six digit number = '))

a=number%10
number=number//10

b==number%10
number=number//10

c=number%10
number=number//10

d=number%10
number=number//10

e=number%10
number=number//10

f=number%10

print(a+b+c+d+e+f)

"""#if else1"""

#write the login second program
email=input('Enter the email')
password=input('Enter the password')
if email =='rsinghlax@gmail.com' and password =='9696':
  print('welcome for joining')
elif email =='rsinghlax@gmail.com' and password !='9696' :
  print('Incorrect password')
  password=input('Enter the password again')
  if password == '1234':
   print('welcome,finally')
  else:
   print('Beta tumse nhi ho payega')
else:
  print("Your email or password is incorrect")

#max of three number
a=int(input('Enter the first number'))
b=int(input('Enter the second number'))
c=int(input('Enter the third number'))
if a>b and a>c:
  print('first value is correct')
elif b>a and b>c:
  print('the second value is correct')
else:
  print('third value is correct')

# min value finding
a=int(input('Enter the first number'))
b=int(input('Enter the second number'))
c=int(input('Enter the third number'))
if a<b and a<c:
  print('first value is correct')
elif b<a and b<c:
  print('the second value is correct')
else:
  print('third value is correct')

#menu driven calculator program
f_num=int(input('enter the 1st number'))
s_num=int(input('enter the 1st number'))
#th_num=int(input('enter the 1st number'))

op=input('Enter the operation')

if op == '+' :
  print('The right answer is=',f_num + s_num)
elif op == '-':
  print('The right answer is=',f_num - s_num)
elif op == '*':
  print('The right answer is=',f_num * s_num)
else:
  print('The right answer is=',f_num / s_num)

"""#Atm software program

"""

email=input('Enter the email')
password=input('Enter the password')
if email =='rsinghlax@gmail.com' and password =='9696':
  print('welcome for joining')
else:
  print("Your email or password is incorrect")

#menu based atm program
 # multiple line string ko triple coat me likha jata hai
menu=input("""
Hi! how can i help you

1. Enter 1 for pin change
2. Enter 2 for baleance cheak
3. Enter 3 for withdrawl
4. Enter 4 for Exit

""")
if menu == '1':
  print('change your pin')
elif menu == '2':
  print('baleance cheak')
elif menu == '3':
  print('For withdrawl')
else:
  print('Exit')

"""# modules"""

#modules me kesi ke likhe gye code ko use krte hai
#esme bhout se funcrion use hote hai math,keyword,date time, random
#These are already written format
# esme hum modules ko import krte hai

#math module
import math
x=math.factorial(4)
print('The factorial of 4 is=',x)
x=math.sqrt(196) #yadi chea to bina kesi aur variable me store kre bhi kiya ja skta hai.
print('The sqrt of 196 is =',x)



#keyword
import keyword
keyword.kwlist

#Es method  se bhi likha ja skta hai.
import keyword
key_word_ki_list=keyword.kwlist
print(key_word_ki_list)

# random module
import random
x=random.randint(5,100)#5 se 100 ke beech koi bhi  random value dene ka kaam krta hai.
print('The random value bitween 5 to 100 many more or single =',x)

#Date and time module
import datetime
print(datetime.datetime.now())
print(help('modules'))

"""#Loop in python"""

#while loop program
#print the table using while loop
number=int(input('Enter the any number'))
i=1
while i<11:
  print(number * i )
  i+=1 #i=i+1

#while loop program
#print the table using while loop
number=int(input('Enter the any number'))
i=1
while i<11:
  print(number,'*',i,'=',number*i )
  i += 1

x=1
while i<3:
  print(x)
  x+=1
else:
    print('limit crossed')

"""# Guessing game"""

# guessing game
#we generate a random variable
#first of all we take some ramdom variablr to user
import random
jackport=random.randint(1,100)
guess=int(input('guess any random value'))
counter = 1
while guess != jackport:


   if guess<jackport:
     print('galat!guess higher')
   else:
     print('galat!guess lower')

    guess=int(input('guess kro'))
    counter+=1
else:
     print('correct guess')
     print('attempt',counter)

"""# python for loop"""

#for loop
for i in range (1,11):
  print (i)